const resources = {
    before: {
        confirm: {
            label: {
                en: `Please confirm the following`,
                fr: `Veuillez vérifier les points suivants`,
                es: `Por favor, confirme lo siguiente`,
                it: `Si prega di confermare la seguente`,
                de: `Bitte bestätigen Sie die folgenden`,
            },
            b_conditions: {
                en: `I am aware of the conditions of the e-visa issuance and the rules of entry, stay and exit with an e-visa`,
                fr: `Je suis conscient du fait que les conditions de l'e-délivrance de visas et les règles d'entrée, de séjour et de sortie avec un e-visa`,
                es: `Soy consciente de las condiciones de la e-emisión de la visa y las reglas de entrada, estancia y salida con un e-visa`,
                de: `Ich bin mir bewusst, die Bedingungen der e-visa-Erteilung und die Regeln für die Einreise, den Aufenthalt und die Ausfahrt mit einem e-Visum`,
                it: `Sono a conoscenza delle condizioni dell'e-il rilascio dei visti e le regole di entrata, la permanenza e l'uscita con una e-visa`,
            },
            b_processing: {
                en: `I agree to the automatic processing, transfer and storage of data provided in the application for e-visa purposes.`,
                fr: `Je suis d'accord pour l'automatique, le traitement, le transfert et le stockage des données fournies dans la demande d'e-visa.`,
                es: `Estoy de acuerdo con el procesamiento automático, transferencia y almacenamiento de los datos proporcionados en la solicitud de e-visado a los efectos.`,
                it: `Accetto il trattamento automatico, il trasferimento e la memorizzazione dei dati forniti nella domanda per e-visto scopi.`,
                de: `Ich Stimme der automatischen Verarbeitung, übertragung und Speicherung von Daten, die in der Anwendung für e-visa-Zwecke.`,
            },
            b_email_notification: {
                en: `I agree to receive automatic messages sent to my personal e-mail address concerning the status of my application and the decision thereon as well as detailed instructions for further steps.`,
                fr: `J'accepte de recevoir des messages automatiques envoyés à mon adresse e-mail personnelle concernant le statut de ma demande et de la décision y relative ainsi que des instructions détaillées pour les étapes ultérieures.`,
                de: `Ich Stimme zu, erhalten Sie automatische Nachrichten, die an meine persönliche e-mail-Adresse über den status meines Antrags und die Entscheidung darüber sowie detaillierte Anweisungen für weitere Schritte.`,
                es: `Estoy de acuerdo en recibir de forma automática los mensajes enviados a mi correo electrónico personal de la dirección sobre el estado de mi solicitud y la decisión al respecto, así como las detalladas instrucciones para los pasos posteriores.`,
                it: `Sono d'accordo per l'invio automatico di messaggi inviati al mio indirizzo e-mail personale) riguardanti lo stato della mia richiesta e la decisione al riguardo così come le istruzioni dettagliate per ulteriori passi.`,
            },
        },
        start_button: {
            en: `Start Your Application`,
            fr: `Démarrez Votre Application`,
            es: `Iniciar La Aplicación`,
            de: `Starten Sie Ihre Anwendung`,
            it: `Avviare L'Applicazione`,
        },
    },
    validations: {
        required: {
            en: `This field is required`,
            fr: `Ce champ est obligatoire`,
            es: `Este campo es obligatorio`,
            de: `Dieses Feld ist erforderlich`,
            it: `Questo campo è obbligatorio`,
        },
        validatePwd: {
            short: {
                en: `Password is too short.(Minium length is 6)`,
                fr: `Le mot de passe est trop court.(Minium longueur est de 6)`,
                es: `La contraseña es demasiado corta.(Minio longitud es de 6)`,
                de: `Passwort ist zu kurz.(Minium Länge ist 6)`,
                it: `La Password è troppo corta.(Minio lunghezza è di 6)`,
            },
            complexity: {
                en: `Password does not meet complexity requirements (at least one alphabetical symbol and one numeric symbol).`,
                fr: `Le mot de passe ne répond pas aux exigences de complexité (au moins un symbole alphabétique et numérique symbole).`,
                es: `La contraseña no cumple los requisitos de complejidad (al menos un símbolo alfabético y uno numérico símbolo).`,
                de: `Kennwort nicht den Komplexitätsanforderungen entsprechen (mindestens eine alphabetische symbol und ein numerisches symbol).`,
                it: `Password non soddisfa i requisiti di complessità (almeno un simbolo alfabetico e uno numerico simbolo).`,
            },
        },
        validatePwdConfirm: {
            notmatch: {
                en: `Password and the password confirmation are not matching up.`,
                fr: `Mot de passe et la confirmation du mot de passe ne correspond pas.`,
                es: `La contraseña y la confirmación de la contraseña no coinciden.`,
                de: `Passwort und Passwort-Bestätigung nicht passen.`,
                it: `La Password e la conferma della password non funzionano.`,
            },
        },
        validateEmailConfirm: {
            notmatch: {
                en: `The confirmation e-mail must match your e-mail address.`,
                fr: `La confirmation par e-mail doit correspondre à votre adresse e-mail.`,
                it: `L'e-mail di conferma deve corrispondere il vostro indirizzo di posta elettronica.`,
                de: `Die Bestätigungs-e-mail müssen mit Ihrem e-mail-Adresse.`,
                es: `El e-mail de confirmación debe coincidir con su dirección de correo electrónico.`,
            },
        },
    },
    citizenCode: {
        label: {
            en: `Nationality`,
            fr: `Nationalité`,
            it: `Nazionalità`,
            es: `Nacionalidad`,
            de: `Nationalität`,
        },
        extra: {
            en: `Please specify the issuing country of the passport that will be used to enter the Russian Federation.`,
            fr: `Veuillez indiquer le pays de délivrance du passeport qui sera utilisé pour entrer dans la Fédération de russie.`,
            it: `Si prega di specificare il paese di emissione del passaporto che verrà utilizzato per entrare nella Federazione russa.`,
            de: `Bitte geben Sie dem ausstellenden Land des Reisepasses verwendet wird zur Eingabe der Russischen Föderation.`,
            es: `Por favor, especifique el país de expedición del pasaporte que se utiliza para entrar en la Federación de rusia.`,
        },
    },
    visitArea: {
        label: {
            en: `Visit area`,
            fr: `Visite de la zone`,
            it: `Zona da visitare`,
            es: `Visita de la zona`,
            de: `Gegend zu besuchen`,
        },
        extra: {
            en: `Choose an area you are going to visit`,
            fr: `Choisissez un endroit que vous allez visiter`,
            it: `Scegliere una zona che si sta per visitare`,
            es: `Elija un área que va a visitar`,
            de: `Wählen Sie einen Bereich, den Sie besuchen werden`,
        },
    },
    language: {
        label: {
            en: `Hints and help language`,
            fr: `Des conseils et de l'aide de la langue`,
            de: `Tipps und Hilfe-Sprache`,
            it: `Aiuto e suggerimenti lingua`,
            es: `Consejos y ayuda de idioma`,
        },
        extra: {
            en: `Select language in which you would like the hints, regarding completion of the application form, to be displayed`,
            fr: `Sélectionnez la langue dans laquelle vous souhaitez que les conseils concernant l'achèvement du formulaire de demande, pour être affiché`,
            es: `Seleccione el idioma en el cual desea que las sugerencias, sobre la cumplimentación del formulario de solicitud, para ser mostrado`,
            de: `Wählen Sie die Sprache, in der Sie möchten die Hinweise, über die Fertigstellung der Applikation, form, angezeigt werden`,
            it: `Selezionare la lingua in cui si desidera che i suggerimenti, per quanto riguarda il completamento del modulo di domanda, per essere visualizzato`,
        },
    },
    pwd: {
        label: {
            en: `Password`,
            fr: `Mot de passe`,
            es: `Contraseña`,
            it: `Password`,
            de: `Passwort`,
        },
        extra: {
            en: `If there are technical issues with the system, or you want to complete your application some other time, you can save your work and later, start where you left off. In order to access your application later, however, you will need: (1) your Application ID, and (2) the password that you will enter on this page.`,
            fr: `Si il y a des problèmes techniques avec le système, ou si vous souhaitez compléter votre demande à un autre moment, vous pouvez enregistrer votre travail et, plus tard, commencer là où vous l'avez laissé. Afin d'accéder à votre demande plus tard, cependant, vous aurez besoin de: (1) votre ID d'Application, et (2) le mot de passe que vous saisissez sur cette page.`,
            es: `Si hay problemas técnicos con el sistema, o desea completar su solicitud en otro momento, usted puede guardar su trabajo y, posteriormente, empezar donde lo dejó. Con el fin de acceder a su solicitud más tarde, sin embargo, será necesario: (1) su ID de la Aplicación, y (2) la contraseña que vamos a entrar en esta página.`,
            de: `Wenn es technische Probleme mit dem system, oder Sie wollen Ihre Anwendung zu einem anderen Zeitpunkt, können Sie Ihre Arbeit speichern, und später, beginnen, wo Sie aufgehört haben. Um den Zugriff auf Ihre Anwendung zu einem späteren Zeitpunkt, jedoch, müssen Sie: (1) Ihre Anwendung ID, und (2) Sie können das Passwort geben Sie auf dieser Seite.`,
            it: `Se ci sono problemi tecnici con il sistema, o se si desidera completare la vostra applicazione in un altro momento, è possibile salvare il vostro lavoro e, successivamente, iniziare a dove avete lasciato. Per accedere alla tua applicazione in un secondo momento, tuttavia, è necessario: (1) il vostro ID di Applicazione, e (2) la password che dovrai inserire in questa pagina.`,
        },
    },
    pwd_confirm: {
        label: {
            en: `Confirm password`,
            fr: `Confirmer le mot de passe`,
            es: `Confirmar contraseña`,
            it: `Conferma password`,
            de: `Kennwort bestätigen`,
        },
        extra: {
            en: `Enter the password confirmation`,
            fr: `Entrez le mot de passe de confirmation`,
            es: `Introduzca la contraseña de confirmación`,
            de: `Geben Sie das Kennwort Bestätigung`,
            it: `Immettere la password di conferma`,
        },
    },
    email: {
        label: {
            en: `Your email`,
            fr: `Votre e-mail`,
            de: `Ihre E-Mail`,
            it: `La tua e-mail`,
            es: `Su correo electrónico`,
        },
        extra: {
            en: `Please indicate your email address`,
            fr: `Veuillez indiquer votre adresse e-mail`,
            it: `Si prega di indicare il vostro indirizzo e-mail`,
            es: `Por favor, indique su dirección de correo electrónico`,
            de: `Bitte geben Sie Ihre E-Mail-Adresse`,
        },
    },
    email_confirm: {
        label: {
            en: `Confirm your personal email`,
            fr: `Confirmer votre adresse email personnelle`,
            de: `Bestätigen Sie Ihre persönliche E-Mail`,
            it: `Confermare la tua e-mail personale`,
            es: `Confirme su correo electrónico personal`,
        },
    },
    visa: {
        section_title: {
            en: `Visa details`,
            fr: `Visa de détails`,
            es: `Detalles de la Visa`,
            de: `Visa-details`,
            it: `Visto dettagli`,
        },
        nationality: {
            label: {
                en: `Nationality`,
                fr: `Nationalité`,
                de: `Nationalität`,
                it: `Nazionalità`,
                es: `Nacionalidad`,
            },
            extra: {
                en: `Enter your citizenship, in accordance with the country or organisation whose passport you will be entering Russian Federation with.`,
                fr: `Entrez votre citoyenneté, en fonction du pays ou de l'organisation dont le passeport vous sera entrée en Fédération de russie avec.`,
                es: `Introduzca su ciudadanía, de acuerdo con el país o la organización, cuyo pasaporte va a estar entrando en la Federación de rusia con.`,
                de: `Geben Sie Ihre Staatsbürgerschaft, in übereinstimmung mit den Landes oder einer organisation, deren Pass Sie werden in der Russischen Föderation mit.`,
                it: `Inserisci il tuo cittadinanza, in conformità con il paese o di un'organizzazione il cui passaporto entrare Federazione russa.`,
            },
        },
        b_ever_loss: {
            label: {
                en: `If you had USSR or Russian nationality at some time please select "yes" and indicate when and why you lost it`,
                fr: `Si vous aviez de l'URSS ou de nationalité russe, à certains moments, veuillez sélectionner "oui" et indiquer quand et pourquoi vous l'avez perdu`,
                de: `Wenn Sie hatte USSR oder der Russischen Nationalität in einer Zeit, wählen Sie bitte "ja" und zeigen, Wann und warum Sie es verloren`,
                it: `Se hai avuto URSS o nazionalità russa, a un certo momento si prega di selezionare "sì" e indicare quando e perché si è perso`,
                es: `Si usted tuvo la URSS o de nacionalidad rusa en algún momento por favor, seleccione "sí" y se indican cuándo y por qué la has perdido`,
            },
            extra: {
                en: `Enter "yes" in this field, if you formerly had USSR or Russian citizenship; if not enter “no”. If yes, please answer the specifying questions.`,
                fr: `Entrez "oui" dans ce secteur, si l'on avait autrefois l'URSS ou de nationalité russe; si pas d'entrée “non”. Si oui, veuillez répondre aux questions précisant.`,
                es: `Escriba "sí" en este campo, si anteriormente había URSS o la ciudadanía rusa; si no escriba "no". Si sí, favor de responder a la especificación de las preguntas.`,
                de: `Geben Sie "ja" in diesem Feld, wenn Sie früher hatte USSR oder der Russischen Staatsbürgerschaft; wenn nicht, geben Sie "no". Wenn ja, beantworten Sie bitte die Angabe Fragen.`,
                it: `Inserire "si" in questo campo, se precedentemente aveva URSS o la cittadinanza russa; se non inserire “no”. Se sì, si prega di rispondere alla specifica domanda.`,
            },
        },
        visa_type: {
            goalsect: {
                label: {
                    en: `Purpose of visit (section)`,
                    fr: `Le but de la visite (section)`,
                    es: `El propósito de la visita (sección)`,
                    it: `Scopo della visita (sezione)`,
                    de: `Zweck des Besuchs (Abschnitt)`,
                },
                extra: {
                    en: `Select your purpose of visit from the top drop menu list. Then from the lower drop menu list choose the specification of your purpose of visit`,
                    fr: `Sélectionnez votre but de la visite à partir du haut dans le menu déroulant de la liste. Puis à partir du bas du menu déroulant de la liste choisir les spécifications de votre but de la visite`,
                    es: `Seleccione su propósito de la visita de la parte superior de la gota de la lista de menú. A continuación, desde la parte inferior del menú desplegable de la lista elija las especificaciones de su propósito de la visita`,
                    de: `Wählen Sie Ihr Zweck des Besuchs aus dem oberen Dropdown-Menü-Liste. Anschließend aus dem unteren Dropdown-Menü wählen Sie die Spezifikation Ihrer Zweck des Besuchs`,
                    it: `Selezionare il vostro scopo di visitare dall'alto caduta di lista del menu. Quindi dal basso un menu a discesa scegliere la specificazione dello scopo della visita`,
                },
            },
            goal: {
                label: {
                    en: `Purpose of visit`,
                    fr: `Le but de la visite`,
                    it: `Scopo della visita`,
                    es: `El propósito de la visita`,
                    de: `Zweck des Besuchs`,
                },
                extra: {
                    en: `Select your purpose of visit from the list`,
                    fr: `Sélectionnez votre but de la visite de la liste`,
                    es: `Seleccione su propósito de la visita de la lista`,
                    de: `Wählen Sie Ihr Zweck des Besuchs aus der Liste aus`,
                    it: `Selezionare il vostro scopo di visitare dalla lista`,
                },
            },
            visakind: {
                label: {
                    en: `Visa category and type`,
                    fr: `Visa de la catégorie et le type`,
                    de: `Visa-Kategorie und-Typ`,
                    es: `La Visa de categoría y tipo de`,
                    it: `Visti di categoria e tipo di`,
                },
                extra: {
                    en: `Select the specification for your purpose of visit`,
                    fr: `Sélectionnez la spécification de l'objet de la visite`,
                    es: `Seleccione la especificación para el propósito de su visita`,
                    de: `Wählen Sie die Spezifikation für Ihren Zweck besuchen`,
                    it: `Selezionare la specifica per il tuo scopo della visita`,
                },
            },
        },
        n_entries: {
            label: {
                en: `Number of entries`,
                fr: `Nombre d'entrées`,
                it: `Numero di voci`,
                es: `Número de entradas`,
                de: `Anzahl der Einträge`,
            },
            extra: {
                en: `Enter the intended number of entries to Russian Federation`,
                fr: `Entrez le nombre d'inscriptions à la Fédération de russie`,
                es: `Introduzca la intención de número de entradas a la Federación de rusia`,
                de: `Geben Sie die vorgesehene Anzahl der Einträge in russische Föderation`,
                it: `Immettere il numero di voci da Federazione russa`,
            },
        },
        entry_date: {
            label: {
                en: `Date of entry into Russia`,
                fr: `Date d'entrée en Russie`,
                es: `Fecha de entrada en Rusia`,
                de: `Datum der Einreise in Russland`,
                it: `Data di entrata in Russia`,
            },
            extra: {
                en: `Enter your intended date of entry to Russia in "dd/mm/yyyy" format`,
                fr: `Entrez votre date prévue d'entrée de la Russie dans "dd/mm/yyyy" format`,
                es: `Introduzca su fecha prevista de entrada a Rusia en "dd/mm/aaaa" `,
                de: `Geben Sie Ihre Einreise nach Russland in "dd/mm/yyyy" - format`,
                it: `Inserisci la tua data di entrata alla Russia, "dd/mm/yyyy" formato`,
            },
        },
        issue_date: {
            label: {
                en: `Date of issue`,
                fr: `Date d'émission`,
                it: `Data di emissione`,
                es: `Fecha de emisión`,
                de: `Datum der Ausstellung`,
            },
            extra: {
                de: `Geben Sie bitte das Ausstellungsdatum Ihres Reisepasses im Format "TT/MM/JJJJ" an`,
                it: `Inserire la data del rilascio del Suo passaporto nel formato “gg/mm/aaaa”`,
                en: ``,
                fr: ``,
                es: ``,
            },
        },
        departure_date: {
            label: {
                en: `Date of exit from Russia`,
                fr: `Date de sortie de la Russie`,
                es: `Fecha de salida de Rusia`,
                de: `Datum der Ausreise aus Russland`,
                it: `Data di uscita dalla Russia`,
            },
            extra: {
                en: `Enter your intended date of entry to Russia in "dd/mm/yyyy" format`,
                fr: `Entrez votre date prévue d'entrée de la Russie dans "dd/mm/yyyy" format`,
                es: `Introduzca su fecha prevista de entrada a Rusia en "dd/mm/aaaa" `,
                de: `Geben Sie Ihre Einreise nach Russland in "dd/mm/yyyy" - format`,
                it: `Inserisci la tua data di entrata alla Russia, "dd/mm/yyyy" formato`,
            },
        },
    },
    personal: {
        section_title: {
            en: `Personal details`,
            fr: `Données personnelles`,
            es: `Datos personales`,
            de: `Persönliche details`,
            it: `Dati personali`,
        },
        citizenCode: {
            label: {
                en: `Nationality`,
                fr: `Nationalité`,
                es: `Nacionalidad`,
                it: `Nazionalità`,
                de: `Nationalität`,
            },
            extra: {
                en: `Please specify the issuing country of the passport that will be used to enter the Russian Federation.`,
                fr: `Veuillez indiquer le pays de délivrance du passeport qui sera utilisé pour entrer dans la Fédération de russie.`,
                it: `Si prega di specificare il paese di emissione del passaporto che verrà utilizzato per entrare nella Federazione russa.`,
                de: `Bitte geben Sie dem ausstellenden Land des Reisepasses verwendet wird zur Eingabe der Russischen Föderation.`,
                es: `Por favor, especifique el país de expedición del pasaporte que se utiliza para entrar en la Federación de rusia.`,
            },
        },
        surname: {
            label: {
                en: `Surname (as in passport)`,
                fr: `Nom de famille (comme dans le passeport)`,
                es: `Apellido (como en el pasaporte)`,
                it: `Cognome (come da passaporto)`,
                de: `Familienname (wie im Reisepass)`,
            },
            extra: {
                en: `Enter your surname using letters of the English alphabet, as shown in your passport`,
                fr: `Saisissez votre nom de famille en utilisant des lettres de l'alphabet anglais, comme indiqué dans votre passeport`,
                es: `Introduzca su apellido con las letras del alfabeto inglés, como se muestra en su pasaporte`,
                de: `Geben Sie Ihren Nachnamen mit Buchstaben des englischen Alphabets, wie in Ihrem Reisepass`,
                it: `Inserisci il tuo cognome con lettere dell'alfabeto inglese, come indicato nel passaporto`,
            },
        },
        firstnames: {
            label: {
                en: `First name, middle names, patronymic names (as in passport)`,
                fr: `Prénom, deuxième prénom, nom patronymique nom (comme dans le passeport)`,
                es: `Nombre, apellido nombres, nombres patronímicos (como en el pasaporte)`,
                it: `Primo nome, secondo nome, cognome nomi (come da passaporto)`,
                de: `Vorname, weitere Vornamen, Vatersnamen Namen (wie im Reisepass)`,
            },
            extra: {
                en: `Enter your first name(s), middle name(s) and/or patronym, using letters of the English alphabet, as shown in your passport`,
                fr: `Entrez votre prénom(s), prénom(s) et/ou patronyme, en utilisant des lettres de l'alphabet anglais, comme indiqué dans votre passeport`,
                es: `Ingresa tu primer nombre(s), inicial del segundo nombre(s) y/o patronym, utilizando las letras del alfabeto inglés, como se muestra en su pasaporte`,
                de: `Geben Sie Ihre Vorname(N), Vorname(N) und/oder patronym, unter Verwendung von Buchstaben des englischen Alphabets, wie in Ihrem Reisepass`,
                it: `Inserisci il tuo nome(s), il secondo nome(s) e/o il suo patronimico, utilizzando le lettere dell'alfabeto inglese, come indicato nel passaporto`,
            },
        },
        b_other_names: {
            label: {
                en: `Have you ever had other names (maiden name, pseudonym, holy order etc.)?`,
                fr: `Avez-vous déjà eu d'autres noms (nom de jeune fille, un pseudonyme, un saint ordre, etc.)?`,
                it: `Hai mai avuto altri nomi (nome da nubile, pseudonimo, santo ordine, etc.)?`,
                de: `Haben oder hatten Sie je andere Namen (Geburtsname, Vornamen, pseudonym, Heiligen Ordnung etc.)?`,
                es: `¿Alguna vez has tenido otros nombres (nombre de soltera, el seudónimo, el santo orden, etc.)?`,
            },
            extra: {
                en: `Have you ever had other names (maiden name, pseudonym, holy order etc.)? If you ever used other names (maiden name, pseudonym, holy order etc.) you must enter them. You should only enter one name in each field. To enter other names please use the option “Add”`,
                fr: `Avez-vous déjà eu d'autres noms (nom de jeune fille, un pseudonyme, un saint ordre, etc.)? Si vous avez déjà utilisé d'autres noms (nom de jeune fille, un pseudonyme, un saint ordre, etc.) vous devez les saisir. Vous ne devez entrer un nom dans chaque champ. Pour entrer d'autres noms, veuillez utiliser l'option “Ajouter”`,
                es: `¿Alguna vez has tenido otros nombres (nombre de soltera, el seudónimo, el santo orden, etc.)? Si alguna vez has usado otros nombres (nombre de soltera, el seudónimo, el santo orden, etc.) usted debe entrar en ellos. Sólo debe introducir un nombre en cada campo. Para ingresar a otros nombres por favor, utilice la opción "Agregar"`,
                de: `Haben oder hatten Sie je andere Namen (Geburtsname, Vornamen, pseudonym, Heiligen Ordnung etc.)? Wenn Sie jemals andere Namen (Geburtsname, Vornamen, pseudonym, Heiligen Ordnung etc.) Sie müssen Sie eingeben. Sie sollten nur geben Sie einen Namen in jedem Bereich. Zu geben Sie die anderen Namen benutzen Sie bitte die option "Hinzufügen"`,
                it: `Hai mai avuto altri nomi (nome da nubile, pseudonimo, santo ordine, etc.)? Se avete mai usato altri nomi (nome da nubile, pseudonimo, santo ordine, etc.) si deve entrare. Si deve solo inserire un nome in ogni campo. Per accedere ad altri nomi, si prega di utilizzare l'opzione “Aggiungi”`,
            },
        },
        sex: {
            label: {
                en: `Sex`,
                fr: `Sexe`,
                it: `Sesso`,
                es: `Sexo`,
                de: `Sex`,
            },
        },
        birth_date: {
            label: {
                en: `Date of birth`,
                fr: `Date de naissance`,
                de: `Geburtsdatum`,
                es: `Fecha de nacimiento`,
                it: `Data di nascita`,
            },
        },
        birth_place: {
            label: {
                en: `Your place of birth`,
                fr: `Votre lieu de naissance`,
                it: `Il tuo luogo di nascita`,
                de: `Ihr Geburtsort`,
                es: `Su lugar de nacimiento`,
            },
            extra: {
                en: `Enter your place of birth, as shown in your passport`,
                fr: `Entrez votre lieu de naissance, comme indiqué dans votre passeport`,
                es: `Introduzca su lugar de nacimiento, como aparece en su pasaporte`,
                de: `Geben Sie Ihren Ort der Geburt, wie in Ihrem Reisepass`,
                it: `Inserisci il tuo luogo di nascita, come indicato nel passaporto`,
            },
        },
        b_born_in_Russia: {
            label: {
                en: `If you were born in Russia, select "yes" and specify when and which country you have immigrated to`,
                fr: `Si vous êtes né en Russie, sélectionnez "oui" et de préciser quand et dans quel pays vous avez immigré au`,
                it: `Se fossi nato in Russia, selezionare "sì" e specificare quando e in quale paese si sono trasferiti a`,
                es: `Si usted nació en Rusia, seleccione "sí" y especificar cuándo y en qué país han emigrado a`,
                de: `Wenn Sie wurden geboren in Russland, wählen Sie "ja" und geben Sie an, Wann und in welchem Land Sie haben eingewandert`,
            },
            extra: {
                en: `If you were born in Russia, answer “yes” and enter the name of the country which you immigrated to and when`,
                fr: `Si vous êtes né en Russie, répondre “oui” et entrez le nom du pays de l'immigré et de quand`,
                es: `Si usted nació en Rusia, responder "sí" y escriba el nombre del país que emigró a y cuando`,
                de: `Wenn Sie wurden geboren in Russland, die Antwort "ja" und geben Sie den Namen des Landes, in dem Sie nach und, wenn`,
                it: `Se fossi nato in Russia, rispondere “sì” e immettere il nome del paese in cui è emigrato e quando`,
            },
        },
    },
    passport: {
        section_title: {
            en: `Passport details`,
            fr: `Les détails du passeport`,
            es: `Detalles del pasaporte`,
            de: `Pass details`,
            it: `Dettagli del passaporto`,
        },
        type: {
            label: {
                en: `Type of passport`,
                fr: `Type de passeport`,
                es: `Tipo de pasaporte`,
                it: `Tipo di passaporto`,
                de: `Typ des Reisepasses`,
            },
            extra: {
                en: `Enter your passport type`,
                fr: `Entrez votre type de passeport`,
                es: `Ingrese su tipo de pasaporte`,
                it: `Inserisci il tuo tipo di passaporto`,
                de: `Geben Sie Ihre passport-Typ`,
            },
        },
        number: {
            label: {
                en: `Passport Number`,
                fr: `Numéro De Passeport`,
                it: `Il Numero Di Passaporto`,
                es: `Número De Pasaporte`,
                de: `Pass-Nummer`,
            },
            extra: {
                en: `Enter your passport number (including the series number)`,
                fr: `Entrez votre numéro de passeport (y compris le numéro de série)`,
                es: `Introduzca su número de pasaporte (incluyendo el número de serie)`,
                de: `Geben Sie Ihre Pass-Nummer (einschließlich der Serien-Nummer)`,
                it: `Inserisci il tuo numero di passaporto (compreso il numero di serie)`,
            },
        },
        issue_date: {
            label: {
                en: `Date of issue`,
                fr: `Date d'émission`,
                de: `Datum der Ausstellung`,
                es: `Fecha de emisión`,
                it: `Data di emissione`,
            },
        },
        expiration_date: {
            label: {
                en: `Date of expiry`,
                fr: `Date d'expiration`,
                it: `Data di scadenza`,
                es: `Fecha de caducidad`,
                de: `Ablauf`,
            },
            extra: {
                de: `Geben Sie bitte das Gültigkeitsdatum Ihres Reisepasses im Format "TT/MM/JJJJ" an`,
                it: `Inserire la data della scadenza del Suo passaporto nel formato “gg/mm/aaaa”`,
                en: ``,
                fr: ``,
                es: ``,
            },
        },
    },
    visit: {
        section_title: {
            en: `Visit details`,
            fr: `Visite de détails`,
            es: `Detalles de la visita`,
            de: `Besuchen details`,
            it: `Visita dettagli`,
        },
        visakind: {
            label: {
                en: `Purpose of visit`,
                fr: `Le but de la visite`,
                es: `El propósito de la visita`,
                de: `Zweck des Besuchs`,
                it: `Scopo della visita`,
            },
            extra: {
                en: `Select your purpose of visit from the list`,
                fr: `Sélectionnez votre but de la visite de la liste`,
                de: `Wählen Sie Ihr Zweck des Besuchs aus der Liste aus`,
                es: `Seleccione su propósito de la visita de la lista`,
                it: `Selezionare il vostro scopo di visitare dalla lista`,
            },
        },
        visitArea: {
            label: {
                en: `Visit area`,
                fr: `Visite de la zone`,
                de: `Gegend zu besuchen`,
                es: `Visita de la zona`,
                it: `Zona da visitare`,
            },
            extra: {
                en: `Choose an area you are going to visit`,
                fr: `Choisissez un endroit que vous allez visiter`,
                de: `Wählen Sie einen Bereich, den Sie besuchen werden`,
                es: `Elija un área que va a visitar`,
                it: `Scegliere una zona che si sta per visitare`,
            },
        },
        entry_date: {
            label: {
                en: `Date of entry into Russia`,
                fr: `Date d'entrée en Russie`,
                de: `Datum der Einreise in Russland`,
                it: `Data di entrata in Russia`,
                es: `Fecha de entrada en Rusia`,
            },
            extra: {
                en: `Enter your intended date of entry to Russia in "dd/mm/yyyy" format`,
                fr: `Entrez votre date prévue d'entrée de la Russie dans "dd/mm/yyyy" format`,
                es: `Introduzca su fecha prevista de entrada a Rusia en "dd/mm/aaaa" `,
                de: `Geben Sie Ihre Einreise nach Russland in "dd/mm/yyyy" - format`,
                it: `Inserisci la tua data di entrata alla Russia, "dd/mm/yyyy" formato`,
            },
        },
        stays: {
            0: {
                name: {
                    en: `Name of the hotel/organization`,
                    es: `Nombre del hotel o de la organización`,
                    de: `Name des Hotels/Organisation`,
                    fr: `Nom de l'hôtel ou de l'organisation`,
                    it: `Nome della struttura/organizzazione`,
                },
                address: {
                    en: `Address of the hotel/organization`,
                    es: `La dirección del hotel o de la organización`,
                    fr: `Adresse de l'hôtel ou de l'organisation`,
                    it: `Indirizzo dell'hotel/organizzazione`,
                    de: `Adresse von hotel/in der Organisation`,
                },
                phone: {
                    en: `Telephone number of the hotel/organization`,
                    fr: `Le numéro de téléphone de l'hôtel ou de l'organisation`,
                    es: `El número de teléfono del hotel o de la organización`,
                    it: `Il numero di telefono del hotel/organizzazione`,
                    de: `Telefonnummer von hotel/in der Organisation`,
                },
                fax: {
                    en: `Fax number of the hotel/organization (if available)`,
                    fr: `Numéro de Fax de l'hôtel ou de l'organisation (si disponible)`,
                    it: `Fax numero di hotel/azienda (se disponibile)`,
                    es: `Número de Fax del hotel/organización (si está disponible)`,
                    de: `Fax-Nummer des Hotels/der Organisation (sofern verfügbar)`,
                },
                email: {
                    en: `E-mail address of the hotel/organization (if available)`,
                    es: `E-mail del hotel/organización (si está disponible)`,
                    it: `E-mail indirizzo dell'hotel/azienda (se disponibile)`,
                    de: `E-mail-Adresse des Hotels/der Organisation (sofern verfügbar)`,
                    fr: `E-mail adresse de l'hôtel ou de l'organisation (si disponible)`,
                },
            },
            1: {
                name: {
                    en: `Family name, first name(s) of the individual`,
                    it: `Cognome, nome(s) del singolo`,
                    fr: `Nom de famille, prénom(s) de la personne`,
                    es: `Apellido, nombre(s) de la persona`,
                    de: `Family name, first name(s) der einzelnen`,
                },
                address: {
                    en: `Address of the individual`,
                    de: `Adresse der einzelnen`,
                    fr: `L'adresse de la personne`,
                    it: `L'indirizzo della persona`,
                    es: `La dirección de la persona`,
                },
                phone: {
                    en: `Telephone number of the individual`,
                    es: `Número de teléfono de la persona`,
                    it: `Il numero di telefono del singolo`,
                    de: `Telefon-Nummer der einzelnen`,
                    fr: `Numéro de téléphone de la personne`,
                },
                fax: {
                    en: `Fax number of the individual (if available)`,
                    it: `Numero di Fax della persona (se disponibile)`,
                    de: `Fax-Nummer der Person (falls vorhanden)`,
                    fr: `Numéro de Fax de la personne (si disponible)`,
                    es: `Número de Fax de la persona (si está disponible)`,
                },
                email: {
                    en: `E-mail address of the individual (if available)`,
                    es: `La dirección de correo electrónico de la persona (si está disponible)`,
                    de: `E-mail-Adresse der Person (falls vorhanden)`,
                    it: `Indirizzo di posta elettronica della singola (se disponibile)`,
                    fr: `E-mail de la personne (si disponible)`,
                },
            },
            label: {
                en: `Intended places of stay in the Russian Federation`,
                fr: `L'intention des lieux de séjour dans la Fédération de russie`,
                it: `Inteso luoghi di soggiorno nella Federazione russa`,
                de: `Bestimmte Orte des Aufenthalts in der Russischen Föderation`,
                es: `La intención de los lugares de estancia en la Federación de rusia`,
            },
            extra: {
                en: `List the intended places of stay in the Russian Federation and relevant contact information. You may list up to 10 places you plan to stay at`,
                fr: `Liste aux endroits prévus de rester dans la Fédération de russie et les informations de contact pertinentes. Vous pouvez inscrire jusqu'à 10 endroits où vous prévoyez de rester à`,
                de: `Liste der vorgesehenen Orten, der Aufenthalt in der Russischen Föderation und die entsprechenden Kontakt-Informationen. Sie können bis zu 10 Orte, die Sie planen, um zu bleiben`,
                es: `Lista de la intención de los lugares de estancia en la Federación de rusia y la información de contacto pertinente. Se pueden incluir hasta 10 lugares que usted planea permanecer en`,
                it: `Elenco previsto luoghi di soggiorno nella Federazione russa e pertinenti informazioni di contatto. Si possono inserire fino a 10 posti dove avete intenzione di rimanere in`,
            },
            code: {
                en: `Type of accommodation`,
                fr: `Type d'hébergement`,
                de: `Art der Unterkunft`,
                es: `Tipo de alojamiento`,
                it: `Tipo di alloggio`,
            },
        },
        b_visited_russia: {
            label: {
                en: `Have you ever visited Russia?`,
                es: `Alguna vez ha visitado Rusia?`,
                fr: `Avez-vous déjà visité la Russie?`,
                de: `Haben Sie schon einmal besucht Russland?`,
                it: `Avete mai visitato la Russia?`,
            },
            extra: {
                en: `Indicate whether you have been in Russia before. If the answer is yes, you will need to indicate how many times you were in Russia and the date of your last trip.`,
                fr: `Indiquer si vous avez été en Russie avant. Si la réponse est oui, vous devez indiquer combien de temps vous avez été en Russie et la date de votre dernier voyage.`,
                es: `Indicar si usted ha estado en Rusia antes. Si la respuesta es sí, usted tendrá que indicar cuántas veces fue en Rusia y la fecha de tu último viaje.`,
                de: `Angeben, ob Sie schon in Russland vor. Wenn die Antwort ja ist, müssen Sie angeben, wie viele Male Sie wurden in Russland und dem Datum Ihrer letzten Reise.`,
                it: `Indicare se sono stati in Russia. Se la risposta è sì, si devono indicare di quante volte sei stato in Russia e la data del tuo ultimo viaggio.`,
            },
        },
    },
    contacts_occupations: {
        section_title: {
            en: `Contacts and occupation`,
            es: `Los contactos y la ocupación`,
            fr: `Les Contacts et la profession`,
            it: `Contatti e occupazione`,
            de: `Kontakte und Beruf`,
        },
        b_resident: {
            label: {
                en: `Do you have a permanent residential address?`,
                de: `Haben Sie eine permanente Wohnadresse?`,
                it: `Hai un indirizzo di residenza permanente?`,
                fr: `Avez-vous une adresse de résidence permanente?`,
                es: `¿Usted tiene un domicilio permanente?`,
            },
            extra: {
                en: `If the answer is yes you will have to indicate the address of residence, telelphone number, fax number, email address.`,
                fr: `Si la réponse est oui, vous devez indiquer l'adresse de résidence, telelphone nombre, numéro de fax, adresse e-mail.`,
                es: `Si la respuesta es sí, usted tendrá que indicar la dirección de residencia, número de teléfono, número de fax, dirección de correo electrónico.`,
                de: `Wenn die Antwort ja ist, werden Sie zur Angabe der Adresse des Wohnsitzes, telelphone-Nummer, fax-Nummer, E-Mail-Adresse.`,
                it: `Se la risposta è sì, devi indicare l'indirizzo di residenza, telelphone, numero di fax, indirizzo di posta elettronica.`,
            },
        },
        b_occupation: {
            label: {
                en: `Do you work (study) in the present time?`,
                de: `Do you work (study) in der heutigen Zeit?`,
                it: `Non si lavora (studio) nel tempo presente?`,
                es: `De trabajo (estudio) en el tiempo presente?`,
                fr: `Vous travaillez à l'étude, dans le temps présent?`,
            },
            extra: {
                en: `If the answer is yes you will have to indicate the work address or place of study, position, address, telephone number, number of fax and email.`,
                fr: `Si la réponse est oui, vous devez indiquer l'adresse de travail ou lieu d'études, poste, adresse, numéro de téléphone, numéro de télécopieur et adresse de courriel.`,
                es: `Si la respuesta es sí, usted tendrá que indicar la dirección del trabajo o lugar de estudio, posición, dirección, número de teléfono, número de fax y correo electrónico.`,
                de: `Wenn die Antwort ja ist, werden Sie geben die Adresse oder den Ort der Studie, position, Anschrift, Telefonnummer, Anzahl der fax-und E-Mail.`,
                it: `Se la risposta è sì, devi indicare l'indirizzo del luogo di lavoro o di studio, posizione, indirizzo, numero di telefono, numero di fax ed e-mail.`,
            },
        },
        b_children: {
            label: {
                en: `Children under 16 years and other relatives written in your passport and travelling with you:`,
                es: `Los niños menores de 16 años y otros familiares escrito en su pasaporte y viajar con usted:`,
                fr: `Les enfants de moins de 16 ans et d'autres parents écrite dans votre passeport et voyager avec vous:`,
                it: `I bambini sotto i 16 anni e gli altri parenti scritto il tuo passaporto e viaggiare con voi:`,
                de: `Kinder unter 16 Jahren und anderen verwandten im Pass geschrieben und das Reisen mit Ihnen:`,
            },
            extra: {
                en: `Indicate "yes" in this field if you travel with children under the age of 16, and other relatives, otherwise select "no". If the answer is yes, you must provide specifying information`,
                fr: `Indiquez "oui" dans ce champ si vous voyagez avec des enfants de moins de 16 ans, et d'autres parents, sinon sélectionnez "non". Si la réponse est oui, vous devez fournir la spécification de l'information`,
                es: `Indicar "sí" en este campo, si usted viaja con niños menores de 16 años de edad, y de otros familiares, de lo contrario, seleccione "no". Si la respuesta es sí, usted debe proporcionar la especificación de la información`,
                de: `Geben Sie "ja" in diesem Feld, wenn Sie Reisen mit Kindern unter dem Alter von 16 Jahren und anderen verwandten, andernfalls wählen Sie "Nein". Wenn die Antwort ja ist, müssen Sie angeben von Informationen`,
                it: `Indicare "sì" in questo campo, se si viaggia con i bambini sotto l'età di 16 anni, e gli altri parenti, in caso contrario, selezionare "no". Se la risposta è sì, è necessario fornire la specifica di informazioni`,
            },
        },
        b_relatives: {
            label: {
                en: `Do you currently have relatives in Russia?`,
                it: `Attualmente hanno parenti in Russia?`,
                es: `Actualmente tiene parientes en Rusia?`,
                fr: `Avez-vous actuellement ont de la famille en Russie?`,
                de: `Tun Sie derzeit haben Verwandte in Russland?`,
            },
            extra: {
                en: `Answer "yes", if you currently have relatives in Russia. If the answer is yes, you must indicate them. You must only enter the information regarding one relative per field. In order to add information regarding other relatives, please use the option "Add"`,
                fr: `Répondre "oui", si vous avez actuellement des parents en Russie. Si la réponse est oui, vous devez les indiquer. Vous devez entrer seulement les informations relatives à par un par domaine. Afin d'ajouter des informations concernant d'autres parents, veuillez utiliser l'option "Ajouter"`,
                es: `Responder "sí", si actualmente tiene parientes en Rusia. Si la respuesta es sí, usted debe indicar en ellos. Sólo debe introducir la información relativa a un pariente por campo. Para agregar información relativa a otros parientes, por favor, utilice la opción "Agregar"`,
                de: `Mit "ja" beantworten, wenn Sie derzeit haben Verwandte in Russland. Wenn die Antwort ja ist, müssen Sie angeben, Sie. Sie müssen nur geben Sie die Informationen bezüglich der relativen pro-Feld. Um Informationen über andere Verwandte, verwenden Sie bitte die option "Hinzufügen"`,
                it: `Rispondere "sì", se si hanno parenti in Russia. Se la risposta è sì, è necessario indicare loro. Devi solo inserire le informazioni per quanto riguarda quella relativa al campo. Per aggiungere informazioni riguardanti altri parenti, si prega di utilizzare l'opzione "Aggiungi"`,
            },
        },
    },
    relatives: {
        section_title: {
            en: `Relatives details`,
            it: `Parenti dettagli`,
            es: `Los parientes más detalles`,
            fr: `Les parents de détails`,
            de: `Verwandten details`,
        },
        b_relatives: {
            label: {
                en: `Do you currently have relatives in Russia?`,
                de: `Tun Sie derzeit haben Verwandte in Russland?`,
                fr: `Avez-vous actuellement ont de la famille en Russie?`,
                it: `Attualmente hanno parenti in Russia?`,
                es: `Actualmente tiene parientes en Rusia?`,
            },
            extra: {
                en: `Answer "yes", if you currently have relatives in Russia. If the answer is yes, you must indicate them. You must only enter the information regarding one relative per field. In order to add information regarding other relatives, please use the option "Add"`,
                fr: `Répondre "oui", si vous avez actuellement des parents en Russie. Si la réponse est oui, vous devez les indiquer. Vous devez entrer seulement les informations relatives à par un par domaine. Afin d'ajouter des informations concernant d'autres parents, veuillez utiliser l'option "Ajouter"`,
                es: `Responder "sí", si actualmente tiene parientes en Rusia. Si la respuesta es sí, usted debe indicar en ellos. Sólo debe introducir la información relativa a un pariente por campo. Para agregar información relativa a otros parientes, por favor, utilice la opción "Agregar"`,
                de: `Mit "ja" beantworten, wenn Sie derzeit haben Verwandte in Russland. Wenn die Antwort ja ist, müssen Sie angeben, Sie. Sie müssen nur geben Sie die Informationen bezüglich der relativen pro-Feld. Um Informationen über andere Verwandte, verwenden Sie bitte die option "Hinzufügen"`,
                it: `Rispondere "sì", se si hanno parenti in Russia. Se la risposta è sì, è necessario indicare loro. Devi solo inserire le informazioni per quanto riguarda quella relativa al campo. Per aggiungere informazioni riguardanti altri parenti, si prega di utilizzare l'opzione "Aggiungi"`,
            },
        },
    },
    appointment: {
        section_title: {
            en: `Appointment details`,
            fr: `Détails du rendez-vous`,
            es: `Los detalles de la cita`,
            de: `Termin details`,
            it: `I dettagli dell'appuntamento`,
        },
        destination: {
            label: {
                en: `Select the location where you will be applying for your visa`,
                de: `Wählen Sie den Speicherort, wo werden Sie Ihre Anwendung für Ihr Visum`,
                it: `Selezionare la posizione in cui si applica per il visto`,
                es: `Seleccione la ubicación donde se va a aplicar para su visa`,
                fr: `Sélectionnez l'emplacement où vous allez faire votre demande de visa`,
            },
            extra: {
                en: `Indicate which Russian Embassy or Consulate where you intend to apply for your visa. Your application will be sent to the selected authority, for a decision to be made regarding your application.`,
                fr: `Indiquer russe de l'Ambassade ou du Consulat où vous avez l'intention de demander votre visa. Votre demande sera envoyée à l'autorité, pour qu'une décision soit rendue au sujet de votre demande.`,
                es: `Indicar a qué Embajada o Consulado ruso en la que va a aplicar para su visa. Su solicitud será enviada a los seleccionados de la autoridad, para que se tome una decisión respecto a su solicitud.`,
                de: `Zeigen die Russischen Botschaft oder Konsulat, wo Sie beabsichtigen, um Ihr Visum zu beantragen. Ihre Bewerbung wird an die gewählte Behörde, für die eine Entscheidung über Ihre Anwendung.`,
                it: `Indicare quale Ambasciata o Consolato russo in cui si intende applicare per il visto. La vostra domanda verrà inviata ai seguenti autorità, per una decisione per quanto riguarda la vostra applicazione.`,
            },
        },
    },
},
